storage: /verdaccio/storage/data
auth:
  htpasswd:
    file: /verdaccio/storage/htpasswd
    max_users: 1
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    # url: https://registry.npm.taobao.org
    # url: https://repo.huaweicloud.com/repository/npm/
    maxage: 10m
    timeout: 30s
    max_fails: 5
    fail_timeout: 10m
    cache: true


packages:
  '@*/*':
    access: $all
    publish: $authenticated
    proxy: npmjs
  '**':
    access: $all
    publish: $authenticated
    proxy: npmjs
logs:
  - {type: stdout, format: pretty, level: http}
